### ISSUE TITLE
Getting GeneralFailure whenever I try to authenticate new accounts

### ISSUE THREAD

**Issue by xagotrunk** [geel9/SteamAuth#13]
I swear I authenticated an account fine just this morning but now I must have tried it 50+ times and I'm getting GeneralFailure whenever it gets to the part where it's supposed to send an SMS code to the phone number. I've tried multiple phone numbers and account and even on different computers. I've even tried using the Steam Desktop Authenticator and it just goes to the main menu whenever the SMS code is supposed to be sent.

Is this an issue with steam servers or the steamauth program?

**Comment by pipe01** [comment]
When you try to log in too many times, steam blocks you from logging for a while, maybe it's that

**Comment by xagotrunk** [comment]
I asked my friend to try it who hasn't logged on at all and got the same result

**Comment by Jessecar96** [comment]
This is a confirmed problem, it's being worked on.

**Comment by geel9** [comment]
Fixed in c4745e365b91205d3b86f3b69e0981da31ee9c44
