### ISSUE TITLE
Problem with authenticate

### ISSUE THREAD

**Issue by Xeroner** [geel9/SteamAuth#15]
http://scr.hu/9li8/ap4ca

Anybody can help?

**Comment by xagotrunk** [comment]
I'm getting the same problem https://github.com/geel9/SteamAuth/issues/13
Its possible steam changed something in the API

**Comment by Xeroner** [comment]
Meaby, but we need to solve this.

**Comment by geel9** [comment]
Fixed in https://github.com/geel9/SteamAuth/commit/c4745e365b91205d3b86f3b69e0981da31ee9c44

**Comment by Xeroner** [comment]
It's not fixed!, it's not working at all, still got this same problem.
