### ISSUE TITLE
Auto Bot

### ISSUE THREAD

**Issue by muratkerimoglu06** [geel9/SteamAuth#22]
Can I use it as bot on jackpot site ? If yes then how ?

Is it accepts trades automatically.

**Comment by ChaosEmperor** [comment]
Please do not post issues without being well informed on the subject.

This is a library used to *help* authenticate automatically and work with confirmations. It is **NOT** a bot. Please search elsewhere for bots.

**Comment by orik007** [comment]
You can buy it
![Autobot](http://vintageactionfigures.com/wp-content/uploads/2013/09/transformers-g1-hound-box.jpg)

**Comment by pipe01** [comment]
Lolol

**Comment by ChaosEmperor** [comment]
Rofl, nice one!
