### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by GreYzZ** [geel9/SteamAuth#24]
So is it true that you cant use this with a Linux bot?

**Comment by pipe01** [comment]
As far as I know,you can but you may have some issues.

**Comment by GreYzZ** [comment]
@pipe01 @geel9 
Any updates about fixes planned?

**Comment by pipe01** [comment]
No idea :\

**Comment by Jessecar96** [comment]
Of course you can, it's already integrated into SteamBot.

**Comment by GreYzZ** [comment]
@Jessecar96 
Ehm one more question I wanted to post this in Steambot but I'm banned for no reason
