### ISSUE TITLE
Failed to generate 2FA code

### ISSUE THREAD

**Issue by sejecbsmurf** [geel9/SteamAuth#27]
Its saying Login Failed to generate 2FA code. Make sure you have linked the authenticator via Steambot.
How do I link the authenticator via steambot?

**Comment by lotfiuser** [comment]
me too

**Comment by orik007** [comment]
read documentation on steambot and here.
Poor moderators need to answer these basic questions over and over and over again, cos people are lazy to read and try first.

**Comment by lotfiuser** [comment]
-_- ok go read them if there is something there i will suicide

**Comment by Jessecar96** [comment]
This is not the SteamBot repo.
