### ISSUE TITLE
How to get maCode

### ISSUE THREAD

**Issue by wolfovik** [geel9/SteamAuth#28]
Sorry for stupid question, but how do I get mobile auth code here:

                        case LoginResult.Need2FA:
                            Console.WriteLine("Please enter your mobile authenticator code: ");
                            code = Console.ReadLine();
                            login.TwoFactorCode = code;
                            break;

**Comment by ChaosEmperor** [comment]
Check your mobile?

**Comment by tarun200897** [comment]
You need the steam app on your mobile or should  use SDA/WinAuth for the two factor code.

**Comment by wolfovik** [comment]
So how could work confirmation of trades , if the account is not tied to SteamAuth? Should I fill .maFile with my mobile data for correct conformations?
