### ISSUE TITLE
It's no longer possible to add phone number

### ISSUE THREAD

**Issue by JustArchi** [geel9/SteamAuth#29]
Check this: https://github.com/JustArchi/ArchiSteamFarm/issues/80
And this: https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/193

```FinalizeAddAuthenticator()``` always returns ```BadSMSCode```

**Comment by ChaosEmperor** [comment]
Just tested it, seems to work fine.

**Comment by JustArchi** [comment]
Yep, most likely temporary issue.
