### ISSUE TITLE
Error exceptions

### ISSUE THREAD

**Issue by Jallvar** [geel9/SteamAuth#31]
For any query. (except for authorization) an error

"An unhandled exception of type "System.NullReferenceException" in SteamAuth.dll
For more information: Object reference not set to an instance of the object."

*Get the latest version from the hub

This error appears on the functions:
RefreshSession()
FetchConfirmations()
then could not check
code:
static void Main(string[] args)
        {
            Console.WriteLine("Имя аккаунта:");
            string account = Console.ReadLine();
            string guardFile = System.IO.File.ReadAllText(account + ".maFile");
            SteamGuardAccount guard = JsonConvert.DeserializeObject<SteamGuardAccount>(guardFile);
            Console.WriteLine("Тип запуска(code,trades):");
            string type = Console.ReadLine();
            Console.Clear();
            switch (type)
            {
                case "code":
                    {
                        while (true)
                        {
                            string code = guard.GenerateSteamGuardCode();
                            Console.WriteLine("{0}", code);
                            System.Threading.Thread.Sleep(30000);
                        }
                    }
                case "trades":
                    {
                        while (true)
                        {
                            if (guard != null)
                                guard.RefreshSession();
                            Confirmation[] tradeRequests = guard.FetchConfirmations();
                            foreach (Confirmation conf in tradeRequests)
                            {
                                guard.AcceptConfirmation(conf);
                            }
                            System.Threading.Thread.Sleep(20000);
                        }
                    }
            }
        }

**Comment by R3PlaaY** [comment]
Yeah, i have this problem. Since i downloaded this program, i couldnt wait to use it. I did everything to verify everything. The main problem it wont show me the Steam-Guard code. Every time when i try to log in, an error occours. My account is gone. Until this Bug is fixed

**Comment by R3PlaaY** [comment]
Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: inputBuffer
   bei System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   bei System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   bei System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   bei System.IO.Stream.Close()
   bei System.IO.Stream.Dispose()
   bei Steam_Desktop_Authenticator.FileEncryptor.DecryptData(String password, String passwordSalt, String IV, String encryptedData)
   bei Steam_Desktop_Authenticator.Manifest.GetAllAccounts(String passKey, Int32 limit)
   bei Steam_Desktop_Authenticator.Manifest.VerifyPasskey(String passkey)
   bei Steam_Desktop_Authenticator.Manifest.PromptForPassKey()
   bei Steam_Desktop_Authenticator.MainForm.MainForm_Shown(Object sender, EventArgs e)
   bei System.Windows.Forms.Form.OnShown(EventArgs e)
   bei System.Windows.Forms.Form.CallShownEvent()
   bei System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbacks()
