### ISSUE TITLE
Getting BadSMSCode when trying to add mobile authenticator even though code is correct

### ISSUE THREAD

**Issue by xagotrunk** [geel9/SteamAuth#32]
I've been getting this error every time I try to input the SMS sent to my phone. I've tried different phone numbers and different accounts but I still get this error every time. Did valve change something with adding authenticators?

**Comment by BlueRaja** [comment]
I am getting the same issue.

Logged the request using Fiddler:

## Request ##
```POST https://api.steampowered.com/ITwoFactorService/FinalizeAddAuthenticator/v0001 HTTP/1.1
Accept: text/javascript, text/html, application/xml, text/xml, */*
User-Agent: Mozilla/5.0 (Linux; U; Android 4.1.1; en-us; Google Nexus 4 - 4.1.1 - API 16 - 768x1280 Build/JRO03S) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Referer: https://steamcommunity.com/mobilelogin?oauth_client_id=DE45CD61&oauth_scope=read_profile%20write_profile%20read_client%20write_client
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Host: api.steampowered.com
Content-Length: 143
Accept-Encoding: gzip, deflate

steamid=76561198116339914&access_token=abcd123etc&activation_code=78214&authenticator_code=&authenticator_time=1453702668```

## Response ##
```HTTP/1.1 200 OK
X-eresult: 1
Content-Type: application/json; charset=UTF-8
Content-Length: 87
Expires: Mon, 25 Jan 2016 06:17:49 GMT
Date: Mon, 25 Jan 2016 06:17:49 GMT
Connection: keep-alive

{
	"response": {
		"success": false,
		"server_time": "1453702669",
		"status": 89
	}
}```

I tried multiple times, I'm certain the SMS code is correct.

**Comment by BlueRaja** [comment]
I also tried [SteamDesktopAuthenticator](https://github.com/Jessecar96/SteamDesktopAuthenticator), but the same thing happens _(which results in an endless loop of it asking for my SMS code + my recovation code)_.

**Comment by BlueRaja** [comment]
**I found a workaround**.  It seems the issue is with linking a phone number.  If I [add a phone number manually](https://store.steampowered.com/phone/manage) beforehand, SteamAuth works correctly.

**Comment by Apostol77794** [comment]
I have exactly the same error
Bot.cs
line 833: var smsCode = WaitForInput(); -->Valid code
line 834:  var authResult = authLinker.FinalizeAddAuthenticator(smsCode); -->BadSMSCode
