### ISSUE TITLE
Steam Parental support

### ISSUE THREAD

**Issue by JustArchi** [geel9/SteamAuth#37]
Currently trying to link an authenticator on steam-parental restricted account results in general failure.

Are there any plans on adding proper support for unlocking steam parental prior to linking new authenticator? I think that a good idea would be to provide extra argument in ```UserLogin``` constructor that would accept string-based parental pin that can unlock given account.

See https://github.com/JustArchi/ArchiSteamFarm/issues/113 for issue.

Check https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/ArchiWebHandler.cs#L545 for example of how I dealt with the issue of unlocking such accounts in my ASF.

Thank you in advance.

**Comment by geel9** [comment]
Will look into.

**Comment by JustArchi** [comment]
Thanks! :+1:
