### ISSUE TITLE
Letting the computer go to sleep or disconnecting the internet results in an unhandled exception.

### ISSUE THREAD

**Issue by impman** [geel9/SteamAuth#39]
As in title. I'm using Steam Desktop Authenticator (can't find the issues page there, I'm assuming it's supposed to go here), and allowing the computer to sleep, or unplugging a network cable, results in the error:

Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

The remote name could not be resolved: 'api.steampowered.com'.

I've attached the error log here.

[errorlog.txt](https://github.com/geel9/SteamAuth/files/166449/errorlog.txt)

**Comment by orik007** [comment]
Seems like app has timer with checking if steam is online.
Not well programmed :-)

**Comment by JustArchi** [comment]
This is SDA bug and not SteamAuth one, it should not be posted here.

**Comment by impman** [comment]
SDA closed all their issues over a month ago and it's impossible to open any more.

**Comment by JustArchi** [comment]
Since when that allows you to go to totally different third-party repo and spam your issues there?

**Comment by impman** [comment]
I wasn't sure if it was a SteamAuth issue or an SDA issue as SDA runs on SteamAuth.

**Comment by JustArchi** [comment]
And that's why I told you that it's SDA bug and it should not be posted here.

If SDA devs closed their issues page then it was their decision and you should not go to third-party library repos and blame those devs there.

**Comment by Shravan2x** [comment]
I agree with @JustArchi , this is *not* the place for this. 

"Do you go to Linus Torvalds and ask about Windows because Bill Gates ignores you?" - iLOL'd
