### ISSUE TITLE
GeneralFailure

### ISSUE THREAD

**Issue by SuperDoker** [geel9/SteamAuth#5]
what is it http://i.imgur.com/8Cb9cCh.png

**Comment by Xeroner** [comment]
It's not solved, why you close it?

**Comment by ChaosEmperor** [comment]
In most cases, `GeneralFailure` means a one-time error of some sort. Like the server returning this one "An error occurred while processing your request.". Just retrying your request should work in most cases.

There are some errors that could probably be better off having their own response. For example, `TooManyFailedLogins`. I have a modified version of the library that has this, but it's completely redesigned so it probably won't do you any good.

Add this on line 128 on UserLogin.cs after making an enum entry.

    if (loginResponse.Message != null && loginResponse.Message.Contains("too many login failures"))
    {
        session.State = LoginResult.TooManyFailedLogins;
        return;
    }

There has also been one more error I've seen which you might want to protect against. Change line 62 of UserLogin.cs to :

    if (rsaResponseJson == null || rsaResponseJson.Contains("<BODY>\nAn error occurred while processing your request.")) session.State = ESessionState.GeneralFailure;

**Comment by EgoTempest** [comment]
I'm having the endless captcha problem, what was the solution for that? I can't see it listed.

**Comment by rumblefrog** [comment]
@EgoTempest You do realize this issue is more than **4** years old? And the last commit is a year old?

**Comment by aleksamagicka** [comment]
This lib is dead, try to find something else
