### ISSUE TITLE
[FIXED] SharedSecret with Backslash "\" issue. SteamGuardAccount.cs fails due to the char is not a valid base64

### ISSUE THREAD

**Issue by speed-str** [geel9/SteamAuth#57]
While the program works great with most shared secrets, i found one particular problem when using a shared secret having "\" Backslash in it. The program throws exception at line 
byte[] sharedSecretArray = Convert.FromBase64String(this.SharedSecret);
Because the character "\" is not a valid base64 and hence it cannot be converted. Any idea on how to achieve it ?

**Comment by Shravan2x** [comment]
Escape characters sometimes get added to the secrets. Just replace it with the escaped value and you should be fine.

**Comment by speed-str** [comment]
sorry if i sound like a complete noob but i've tried replacing the backslash and it still doesn't work. i found on the internet that replace wont work on the backslash. I've been trying this: 

string text = Console.ReadLine();
text.Replace("\\", "");
text.Replace("\"", "");

**Comment by Shravan2x** [comment]
You're replacing it with *nothing*. That's not what you need to do. You need to *escape* the *escape character*.

**Comment by BlueRaja** [comment]
It sounds like the string needs to be run through [Regex.Unescape](https://msdn.microsoft.com/en-us/library/system.text.regularexpressions.regex.unescape(v=vs.110).aspx)

**Comment by speed-str** [comment]
@BlueRaja Sweet ! i used that method and it worked like a charm, here is what i was doing

string SharedSecretUnescaped = Regex.Unescape(SharedSecretEscaped);
byte[] sharedSecretArray = Convert.FromBase64String(SharedSecretUnescaped);

Should we create a pull request ?

**Comment by BlueRaja** [comment]
A PR would make sense, yeah

**Comment by speed-str** [comment]
PR created
