### ISSUE TITLE
cloning on Linux does not include /lib/SteamAuth

### ISSUE THREAD

**Issue by Xetrics** [geel9/SteamAuth#64]
The lib/SteamAuth folder is empty when cloning the project.... I am able to fix this by cding into the lib directory then running

> git clone https://github.com/geel9/SteamAuth.git .

**Comment by BlueRaja** [comment]
It is not included in /lib, it's a Nuget dependency (along with SteamKit and JSON.net).  It shouldn't be added by cloning.  You'll need to install the dependencies through NuGet _(not sure how that's done in Linux - in Visual Studio it's done automatically when building)_

**Comment by BlueRaja** [comment]
_(whoops I didn't realize what repo this was - ignore my previous comment)_

**Comment by Xetrics** [comment]
It was my mistake too..... opening it in the wrong repo.
