### ISSUE TITLE
Could we have NuGet SteamAuth updated?

### ISSUE THREAD

**Issue by nightfuryninja** [geel9/SteamAuth#74]
Hello, I was wondering if we could get the NuGet Version of SteamAuth updated to the latest version on here for ease when we build the SteamBot after redownloading it? Could anyone who has access do that?

**Comment by BlueRaja** [comment]
I am the manager of that package, but I have no insight into this project so it would be best if someone from the project (particularly @geel9) would take it over.

Please contact me, and I can get you setup with permissions.
