### ISSUE TITLE
No way to tell incorrect captcha from incorrect login

### ISSUE THREAD

**Issue by Pwntastic** [geel9/SteamAuth#9]
It doesn't look like there's any way to tell the difference between the login results from an incorrect login with valid captcha and a valid login with incorrect captcha. they both return NeedCaptcha.

I realize valve don't have a separate flag on the login response, but the message returned is different between the two.

Valve return "Please verify your humanity by re-entering the characters below." if the login was correct but the captcha was wrong, and "Incorrect login." if the login was wrong and the captcha correct.

**Comment by geel9** [comment]
Will attempt to resolve.

**Comment by charredgrass** [comment]
Can confirm, same happening with me.

**Comment by ChaosEmperor** [comment]
You can insert the following fixes in UserLogin.cs.

On line 191:

    [JsonProperty("message")]
    public string Message { get; set; }

On line 108:

    if (loginResponse.Message != null && loginResponse.Message.Contains("Incorrect login"))
        return LoginResult.BadCredentials;

**Comment by Jessecar96** [comment]
Fixed with #17
