### ISSUE TITLE
Fail to add authenticator in new version of the rest api

### ISSUE THREAD

**Issue by Zachxz0** [geel9/SteamAuth#93]
/ITwoFactorService/AddAuthenticator/v0001 report HTTP 401

**Comment by Skr1pt** [comment]
Steam delete OAuth token, so now this old api didnt worked

**Comment by Jack-256** [comment]
@Skr1pt Is there any other way to solve it

**Comment by Skr1pt** [comment]
re-write bot for new api, but its use protobuf and encoding 
![image](https://github.com/geel9/SteamAuth/assets/44027401/f0118378-44fe-4a0f-abbc-498d5d07b4b8)

**Comment by Jack-256** [comment]
Can you show more detail about how to post the data?  where to get the access_token

**Comment by Jack-256** [comment]
@Skr1pt Can you show more detail about how to post the data? where to get the access_token

**Comment by Skr1pt** [comment]
https://api.steampowered.com/ITwoFactorService/AddAuthenticator/v1?access_token=eyAidHlwIjogIkpXVCIsICJhbGciOiAiRWREU0EiIH0.eyAiaXNzIjogInI6MEI3OF8yMTMwMTRGN182QkE4OCIsICJzdWIiOiAiNzY1NjExOTkyNDc3MDI4MTgiLCAiYXVkIjogWyAid2ViIiwgIm1vYmlsZSIgXSwgImV4cCI6IDE2NjE1MDM2MTIsICJuYmYiOiAxNjYxNDE2MzA2LCAiaWF0IjogMTY2MTQxNjMxNiwgImp0aSI6ICIwQjc4XzIxMzAxNEY3XzZCQzZGIiwgIm9hdCI6IDE2NjE0MTYzMTUsICJydF9leHAiOiAxNjc5NjM4OTc3LCAicGVyIjogMCwgImlwX3N1YmplY3QiOiAiOTIuNTIuMTQ2LjE1MSIsICJpcF9jb25maXJtZXIiOiAiOTIuNTIuMTQ2LjE1MSIgfQ.E4brrmQRw-qh52FQ_GbcOfpH7bTI-SA8q1P8yWSuArtSZBPbB95Hds3u1atAagDTqIPd_qxrmxdOL7eYya4pBQ

**Comment by Skr1pt** [comment]
idk where get access token

**Comment by Jack-256** [comment]
> idk where get access token
😱 but you actually had it in the url

**Comment by Skr1pt** [comment]
I caught this requests ~1 year ago

**Comment by Skr1pt** [comment]
i think this repo can help u
https://github.com/DoctorMcKay/node-steamcommunity/blob/353156008391f8474212681e381c275a81dacd57/components/twofactor.js#L19

**Comment by Zachxz0** [comment]
> i think this repo can help u https://github.com/DoctorMcKay/node-steamcommunity/blob/353156008391f8474212681e381c275a81dacd57/components/twofactor.js#L19

So helpful, thanks, I will take a look! 😀

**Comment by Zachxz0** [comment]
@Skr1pt It works, but it's really disgusting for more difficulty！

**Comment by Zachxz0** [comment]
@Jessecar96 https://github.com/DoctorMcKay/node-steamcommunity/blob/353156008391f8474212681e381c275a81dacd57/components/twofactor.js#L19

**Comment by Zachxz0** [comment]
@Skr1pt 
![capture](https://github.com/geel9/SteamAuth/assets/13977847/14d81952-c3a1-49f7-a77c-e14c540f163e)
Warned！！！😓

**Comment by Jessecar96** [comment]
This is resolved in the latest commits.
