### ISSUE TITLE
Login Web Request response in HTML instead of JSON, crashing program

### ISSUE THREAD

**Issue by lorppijw** [geel9/SteamAuth#95]
I still keep having this problem where this:
string response = SteamWeb.Request(APIEndpoints.COMMUNITY_BASE + "/steamguard/phoneajax", "POST", postData, _cookies);
returns a steam html page instead of a json response when I try to setup a new account.

Newtonsoft.Json.JsonReaderException: 'Unexpected character encountered while parsing value: <. Path '', line 0, position 0.'

**Comment by Jessecar96** [comment]
This is resolved in the latest commits. We use IPhoneService now like the app does.
