### ISSUE TITLE
About AuthenticatorLinker.cs#L112

### ISSUE THREAD

**Issue by jwcloverain** [geel9/SteamAuth#97]
https://github.com/geel9/SteamAuth/blob/b1fc94daf33af33e39d45c645ce41a10c91c189b/SteamAuth/AuthenticatorLinker.cs#L112
I see countryCode is getting from _getUserCountry, but can't link a number that is different from the country of the account

**Comment by Jessecar96** [comment]
This is the way the official Steam app does it so that's what I went for.
